version: '3'

services:
  frontend:
    container_name: frontend
    image: node:18-alpine
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  api:
    container_name: api
    image: composer
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "composer install && php artisan serve --host 0.0.0.0"
